### ISSUE TITLE
failed to interact with element find by descendant 

### ISSUE THREAD

**Issue by baovu2512** [appium-flutter-driver/appium-flutter-driver#119] opened 2020-11-20 08:10 UTC
I'm trying to find by descendant but maybe is not working anymore.
`MobileElement  el = find.descendant(find.byTooltip("counter_tooltip"), find.byValueKey("counter"));
    el.click();
    el.getText();`

Any interact with element find by descendant will throw below exception: 
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command tap, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing tap: NoSuchMethodError: The getter 'length' was called on null.\nReceiver: null\nTried calling: length\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)\n#1      _parseJson (dart:convert-patch/convert_patch.dart:39:28)\n#2      JsonDecoder.convert (dart:convert/json.dart:505:36)\n#3      JsonCodec.decode (dart:convert/json.dart:156:41)\n#4      jsonDecode (dart:convert/json.dart:96:10)\n#5      Descendant.deserialize (package:flutter_driver/src/common/find.dart:357:34)\n#6      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/find.dart:24:44)\n#7      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:51:30)\n#8      new Tap.deserialize (package:flutter_driver/src/common/gesture.dart:14:93)\n#9      new FlutterDriverExtension.<anonymous closure> (package:flutter_driver/src/extension/extension.dart:213:50)\n#10     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:267:50)\n#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:547:32)\n<asynchronous suspension>\n#12     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)\n#13     _runExtension (dart:developer-patch/developer.dart:84:23)\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```

**Comment by shibupanda** [comment] 2020-11-20 08:32
@baovu2512 could you please share the logs I may check some of the pending PR and Issues in weekend.

**Comment by baovu2512** [comment] 2020-11-20 08:45
<script src="https://gist.github.com/baovu2512/8684a768d537d25773e188fe795183cd.js"></script>

**Comment by baovu2512** [comment] 2020-11-22 03:15
Hi @shibupanda , any update on this ?

**Comment by shibupanda** [comment] 2020-11-22 03:28
@baovu2512 looks like the issue is from dart api. Could you please share the details of your environment like dart , flutter version.
And add flutter-doctor output also it will be easy to raise in flutter community.
And please try the test using flutter driver(not appium) also.

Found one article on the same. https://www.mmbyte.com/article/72112.html

**Comment by baovu2512** [comment] 2020-11-22 03:32
Flutter 1.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (6 weeks ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1
Windows 10
Appium 1.18.2
Appium flutter: lastest

I've tried flutter driver also, its work fine.

**Comment by shibupanda** [comment] 2020-11-22 03:54
Could you please send flutter driver logs as well. And Appium flutter driver latest you mean 0.0.25?

**Comment by baovu2512** [comment] 2020-11-22 05:15
Sorry, I can't provide flutter driver logs.

Appium flutter : 0.0.26-dev

print( await driver.getText(find.descendant(
          matching: find.byValueKey("sub-title-text"),
          of: find.byValueKey("status-transaction-detail"))));
here is the code in flutter driver. print exactly what I looking for

**Comment by baovu2512** [comment] 2020-11-22 05:25
the shorten one with find descendant only ->
{command: get_text, finderType: Descendant, of: {"finderType":"ByType","type":"Tooltip"}, matching: {"finderType":"ByType","type":"Text"}, matchRoot: false, firstMatchOnly: false}
@shibupanda

**Comment by baovu2512** [comment] 2020-11-22 05:26
maybe we missing the matchRoot and firstMatch i think. the dart throwing error that we are missing some value

**Comment by shibupanda** [comment] 2020-11-22 05:28
Need to check because previously it had default value.

**Comment by baovu2512** [comment] 2020-11-22 05:31
Thanks, can you have a quick check. I'm stuck at and tomorrow is my deadline haha.
Also, can you take a look at https://github.com/truongsinh/appium-flutter-driver/pull/111.

**Comment by shibupanda** [comment] 2020-11-22 16:32
@baovu2512 could you please use some other finders for now. I am outside for few days.

**Comment by baovu2512** [comment] 2020-12-01 02:41
Hi @shibupanda, I notice that you approved the PR, can you publish to npm.
And how about find descendant, do you have any update

**Comment by baovu2512** [comment] 2021-01-13 10:24
@shibupanda , do you have any update.

**Comment by shibupanda** [comment] 2021-01-13 10:26
@baovu2512 I was really blocked with some other tasks we can publish along with iOS fixes.

**Comment by KazuCocoa** [comment] 2021-08-20 08:09
Possible duplicate of https://github.com/appium-flutter-driver/appium-flutter-driver/issues/161

**Closed by KazuCocoa** 2021-08-20 08:09 UTC
Labels: NeedInfo
